### PR TITLE
Adding scrutinizer

### PR DESCRIPTION
**Pull request by spekulatius**

### CODE REVIEW

**Comment by aik099** [comment]
We already have a config defined on Scrutinizer website. Can add these options there instead.

**Comment by spekulatius** [comment]
Hello @aik099 

thanks for your response. If you define the configuration on the Scrutinizer website it only applies to your repository while a file would apply for all forks as well.

Spek

**Comment by aik099** [comment]
It will apply for all PRs as well. Not sure why you need it to run on a fork.

**Comment by davedevelopment** [comment]
:+1: from me

**Comment by aik099** [comment]
I've added changes to the repo config file on Scrutinizer CI website and executed the inspection with new config: https://scrutinizer-ci.com/g/hamcrest/hamcrest-php/inspections/ecb5376f-7740-4e83-9d93-9383d57d1385 . Due strange logic in Scrutinuzer CI you can't rerun inspection that needs external code coverage.

**Comment by aik099** [comment]
@spekulatius , thanks for your contribution.

**Pull request closed without merging**
