### PR TITLE
Documented use of global proxy-functions

### LINKED ISSUE #50: Removed autoloading of functions?
From `CHANGES.txt`:

```
== Version 2.0: Released XXX XX 2016 ==

* Removed automatic loading of global functions
```

Why?

What's the alternative?

There's no mention in the documentation of how to get this package working - global functions are used everywhere in the `README.md`, and those examples simply don't work.

### PR DESCRIPTION
**Pull request by mindplay-dk**
Closes #50

### CODE REVIEW

**Comment by aik099** [comment]
Have the  example, that was using classes instead of global functions worked?

**Comment by mindplay-dk** [comment]
@aik099 not sure what you mean? I use the global functions, same as before - those work fine.

**Comment by aik099** [comment]
I see. I thought, that PR would change all examples not to use global functions. Can I merge this PR?

**Comment by davedevelopment** [comment]
@aik099 can for me :+1:

**Comment by mindplay-dk** [comment]
> I thought, that PR would change all examples not to use global functions

That would make the examples extremely noisy and hard to read.

(I don't know why anybody wants the class-static methods in the first place, but, that's just me 😉)

**Comment by aik099** [comment]
> (I don't know why anybody wants the class-static methods in the first place, but, that's just me 😉)

@mindplay-dk , that is because Hamcrest global functions conflicted with PHPUnit's global functions with same names. For only that reason we've removed auto-loading of them. If the issue was fixed on PHPUnit side (by not using global functions), then it can be used without issues with PHPUnit.

**Comment by aik099** [comment]
Merged. Thanks, @mindplay-dk .

**Comment by mindplay-dk** [comment]
> If the issue was fixed on PHPUnit side (by not using global functions), then it can be used without issues with PHPUnit.

I guess the real problem is using global functions without a namespace - if these were namespaced, you wouldn't risk collisions with PHPUnit; instead, you'd import the functions with `use function` statements, which would make the call-sites look much nicer anyhow.

That's another big BC break of course, but... probably what it should have been in the first place?

**Comment by mindplay-dk** [comment]
> If the issue was fixed on PHPUnit side (by not using global functions), then it can be used without issues with PHPUnit.

I guess the real problem is using global functions without a namespace - if these were namespaced, you wouldn't risk collisions with PHPUnit; instead, you'd import the functions with `use function` statements, which would make the call-sites look much nicer anyhow.

That's another big BC break of course, but... probably what it should have been in the first place?

**Comment by mindplay-dk** [comment]
> If the issue was fixed on PHPUnit side (by not using global functions), then it can be used without issues with PHPUnit.

I guess the real problem is using global functions without a namespace - if these were namespaced, you wouldn't risk collisions with PHPUnit; instead, you'd import the functions with `use function` statements, which would make the call-sites look much nicer anyhow.

That's another big BC break of course, but... probably what it should have been in the first place?

**Comment by mindplay-dk** [comment]
> If the issue was fixed on PHPUnit side (by not using global functions), then it can be used without issues with PHPUnit.

I guess the real problem is using global functions without a namespace - if these were namespaced, you wouldn't risk collisions with PHPUnit; instead, you'd import the functions with `use function` statements, which would make the call-sites look much nicer anyhow.

That's another big BC break of course, but... probably what it should have been in the first place?

**Comment by mindplay-dk** [comment]
> If the issue was fixed on PHPUnit side (by not using global functions), then it can be used without issues with PHPUnit.

I guess the real problem is using global functions without a namespace - if these were namespaced, you wouldn't risk collisions with PHPUnit; instead, you'd import the functions with `use function` statements, which would make the call-sites look much nicer anyhow.

That's another big BC break of course, but... probably what it should have been in the first place?

**Pull request merged**
