### PR TITLE
Prevent imcompatibilities in the future with new versions of php

### PR DESCRIPTION
**Pull request by mikeSimonson**

### CODE REVIEW

**Comment by aik099** [comment]
Build fails.

**Comment by davedevelopment** [comment]
:+1: 

@aik099 only because of a third party lib requiring a higher version of PHP? Probably affects the master branch and could be handled in a separate issue.

**Comment by aik099** [comment]
I've sent #33 to solve this. If build passes in there, then I guess we need to:

* merge it
* rebase this PR against master to make builds pass

**Comment by mikeSimonson** [comment]
@aik099 fixed

**Comment by aik099** [comment]
@mikeSimonson , you do read other other comments, like one where I agreed with @davedevelopment to make this a separate PR and sent it, right?

**Comment by mikeSimonson** [comment]
I had already sent the fix before to see the other comment.
Sorry

**Comment by aik099** [comment]
That's ok. Please rollback last change then.

**Comment by aik099** [comment]
Please rebase, because a fix has been committed to fix Composer error, that is happening.

**Comment by mikeSimonson** [comment]
@aik099 it's done.

**Comment by aik099** [comment]
Looks good. Merging. Thanks @mikeSimonson .

**Pull request merged**
