### PR TITLE
Allow installation of PHPUnit 8 in order to test with PHP 8.1 and 8.2

### PR DESCRIPTION
**Pull request by villfa**
This PR allows the installation of PHPUnit 8.

After installation, when executed, it generates warnings and mark some tests as risky though.

Please tell me if you prefer they are fixed with this PR or in a subsequent one.

To be honest I didn't go further because I first wanted to be sure the project is still maintained.

### CODE REVIEW

**Comment by aik099** [comment]
@villfa , have the changes you've made introduced these risky tests or warnings?

**Comment by villfa** [comment]
No, it's just PHPUnit 8 being stricter than the previous versions.

**Comment by aik099** [comment]
I've marked PR as approved. I'll wait for other maintainers to review it as well.

**Comment by villfa** [comment]
> I'll wait for other maintainers to review it as well.

It has been 2 months. Should we ping some of them?

**Comment by aik099** [comment]
@villfa , let's merge it.

**Pull request merged**
